"""Add bot-specific approval fields

Revision ID: 72afe4101a2c
Revises: 08825ec833a7
Create Date: 2025-01-24 01:53:22.556344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72afe4101a2c'
down_revision = '08825ec833a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precision_master_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('trend_warrior_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pattern_hunter_approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pattern_hunter_approved')
        batch_op.drop_column('trend_warrior_approved')
        batch_op.drop_column('precision_master_approved')

    # ### end Alembic commands ###
